name: Collect ubuntu browser dependencies
on:
    schedule:
        - cron: 0 0 1 * *
permissions:
    pull-requests: write
jobs:
    collect:
        name: Collect browser dependencies
        runs-on: ${{ matrix.os }}
        env:
            BRANCH_NAME: resolve-ubuntu-dependencies-${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  token: ${{ secrets.GH_ACCESS_TOKEN }}
            - name: Setup Node JS
              uses: actions/setup-node@v2
              with:
                  node-version: 18
                  registry-url: https://registry.npmjs.org
            - name: Prepare Ubuntu
              run: sudo apt-get update && sudo apt-get install -y apt-file && sudo apt-file update
            - run: npm ci
            - name: Config git
              run: git config --global user.name "y-infra" && git config --global user.email "y-infra@yandex.ru"
            - name: Fetch branches
              run: git fetch --all
            - name: Checkout to branch
              run: |
                  if git ls-remote --heads origin "$BRANCH_NAME" | grep -q "$BRANCH_NAME"; then
                      git checkout ${{ env.BRANCH_NAME }}
                      git pull
                  else
                      git checkout -b ${{ env.BRANCH_NAME }}
                  fi
            - run: npm run resolve-ubuntu-dependencies
            - run: git add src
            - name: Commit changes
              run: |
                  git status
                  if git diff-index --quiet HEAD src; then
                      echo 'No changes'
                  else
                      echo 'Committing changes'
                      git commit src -m 'chore: update local browser dependencies for ${{ matrix.os }}'
                      git push origin ${{ env.BRANCH_NAME }}
                      gh pr create -B master -H ${{ env.BRANCH_NAME }} --title "Auto update local browser deps for ${{ matrix.os }}" --body "Created by Github action" || echo "Could not create PR. Seems like it already exists"
                  fi
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
