name: Collect ubuntu browser dependencies
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
jobs:
    collect:
        name: Collect browser dependencies
        runs-on: ${{ matrix.os }}
        env:
            BRANCH_NAME: resolve-ubuntu-dependencies-${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node JS
              uses: actions/setup-node@v2
              with:
                  node-version: 18
                  registry-url: https://registry.npmjs.org
            - run: sudo apt-get update
            - run: sudo apt-get install -y fontconfig
            - run: npm ci
            - run: npm run build
            - run: cd e2e-test && npm i && DEBUG=testplane:browser-installer npx testplane install-deps && DEBUG=testplane:browser-installer WDIO_LOG_LEVEL=error npx testplane --local
